# Generated by Django 5.0.6 on 2024-07-08 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AC_Creation_date', models.DateTimeField(auto_now_add=True)),
                ('AC_AccoutType', models.CharField(blank=True, choices=[('Savings', 'Savings'), ('Current', 'Current')], default='Savings', max_length=20, null=True)),
                ('AC_balance', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TC_credit_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('TC_debit_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('TC_type', models.CharField(blank=True, max_length=100, null=True)),
                ('TC_date', models.DateTimeField(auto_now_add=True)),
                ('TC_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='banking.account')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UP_UserName', models.CharField(blank=True, max_length=200, null=True)),
                ('UP_UserAdress', models.CharField(blank=True, max_length=10000, null=True)),
                ('UP_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('UP_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('UP_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='AC_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='banking.userprofiles'),
        ),
    ]
