# Generated by Django 5.0.6 on 2024-07-17 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_account_ac_accoutnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='TC_account',
        ),
        migrations.AddField(
            model_name='transactions',
            name='TC_receiver_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='banking.account'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='TC_sender_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to='banking.account'),
        ),
    ]
