# Generated by Django 5.0.6 on 2024-07-17 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_remove_transactions_tc_account_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='TC_credit_amount',
            new_name='TC_amount',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='TC_debit_amount',
        ),
    ]
